spring:
  application:
    name: Spring Boot Java Project (Consumer)
  main:
    banner-mode: off
    web-application-type: none # disable web server
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: false
  kafka:
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS}"

logging:
  level:
    root: warn

# Custom environment variables
custom:
  target-resolution-count: 6
  path:
    project-root-dir: ${CUSTOM_PATH_PROJECT_ROOT_DIR}
  ffmpeg:
    path: ${FFMPEG_PATH}
    probe: ${FFPROBE_PATH}
aws:
  credentials:
    profile: ${AWS_PROFILE:default}
    region: ${AWS_DEFAULT_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

# /opt/homebrew/bin/ffmpeg for macos
# /usr/bin/ffmpeg for linux
